name: CI/CD Pipeline

# Trigger the workflow when code is pushed to the 'main' branch or a PR is made to 'main'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest  

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2  # Action to checkout the repository

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21'  # Specify the Node.js version to use

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install  # Install dependencies using npm

      # Step 4: Run tests (if applicable)
      - name: Run tests
        run: npm test  # Run tests if you have any test scripts

      # Step 5: Lint the code (optional, if you use ESLint or similar)
      - name: Lint code
        run: npm run lint  # Run linting (optional, remove if not needed)

      # Step 6: Build the project (if applicable)
      - name: Build project
        run: npm run build  # Run the build script (remove if not applicable)

      # Step 7: Deploy to production
      - name: Deploy to Production
        run: |
          echo "Deploying to production..."
          # Add your deployment script here (e.g., rsync, SSH commands)
